# Generated by Django 6.0.6 on 2026-07-10 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('medico_id', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('nombres', models.CharField(max_length=80)),
                ('apellidos', models.CharField(max_length=100)),
                ('especialidad', models.CharField(choices=[('MG', 'Medicina General'), ('PED', 'Pediatría'), ('GIN', 'Ginecología'), ('CAR', 'Cardiología'), ('DER', 'Dermatología'), ('TRA', 'Traumatología')], max_length=3)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('correo_electronico', models.EmailField(blank=True, max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
                'db_table': 'medico',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('paciente_id', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('nombres', models.CharField(max_length=80)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('correo_electronico', models.EmailField(blank=True, max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'paciente',
                'ordering': ['apellidos', 'nombres'],
                'indexes': [models.Index(fields=['cedula'], name='paciente_cedula_4220c9_idx'), models.Index(fields=['apellidos', 'nombres'], name='paciente_apellid_ee766d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('cita_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('estado', models.CharField(choices=[('PRO', 'Programada'), ('ATE', 'Atendida'), ('CAN', 'Cancelada')], default='PRO', max_length=3)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='pacientes.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'db_table': 'cita',
                'ordering': ['-fecha', '-hora'],
                'constraints': [models.UniqueConstraint(fields=('medico', 'fecha', 'hora'), name='unica_cita_medico_horario')],
            },
        ),
    ]
