# Generated by Django 6.0.6 on 2026-07-11 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='paciente',
            field=models.ForeignKey(blank=True, help_text='Opcional: relaciona este cliente con su registro de paciente para evitar datos duplicados.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='pacientes.paciente', verbose_name='Paciente vinculado'),
        ),
    ]
