# Generated by Django 6.0.6 on 2026-07-11 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('MEDICO', 'Médico'), ('RECEP', 'Recepcionista')], default='RECEP', max_length=10, verbose_name='rol'),
        ),
    ]
